Precompile with @kaliber/pack
kaliberjs/safe-json-stringify pull request #3
Opened 2022-07-28 10:57 UTC by HJSielcken

Op dit moment werkt typehinting niet wanneer es-import syntax wordt gebruikt. Door de library door kaliber/pack te halen, werkt typehinting met commonjs en es-module syntax.
de lib folder staat in .gitignore, dus `yarn kaliber-pack` moet gerund worden voordat je het test. Als deze is goedgekeurd push ik de geprecompileerde versie naar npm met versienummer 1.0.0 (in principe is deze pr backwards compatible, maar je weet maar nooit).

2022-07-28 14:38 UTC, larsvankleef requested changes

2022-07-28 14:38 UTC, larsvankleef commented on package.json
> +    "build": "kaliber-pack"
Check even hoe dit bij de cache library is ingesteld, volgens mij bouwt hij daar automatische voor dat je een release doet naar npm

2022-07-29 06:30 UTC, peeke commented
> push ik de geprecompileerde versie naar npm met versienummer 1.0.0

Hij staat nu op `1.1.3`, dus ik denk dat je `2.0.0` bedoeld :)

2022-07-29 06:31 UTC, peeke approved these changes
Goed comment van Lars, verder approved :+1:

2022-07-29 07:56 UTC, merged